FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN useradd -m appuser
USER appuser

EXPOSE 5000

ENV OPTION_A=Cats
ENV OPTION_B=Dogs

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"] 

