apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: vote

  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: OPTION_A
              valueFrom:
                configMapKeyRef:
                  name: voting-config
                  key: OPTION_A

            - name: OPTION_B
              valueFrom:
                configMapKeyRef:
                  name: voting-config
                  key: OPTION_B

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: voting-config
                  key: REDIS_HOST

          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
