apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: hamid009/worker-app:f81bc5bf1c0b491bd483669494590fa9a9a97e98
          imagePullPolicy: Always

          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: voting-config
                  key: REDIS_HOST

            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: voting-config
                  key: POSTGRES_HOST

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: voting-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: voting-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: voting-secret
                  key: POSTGRES_DB

          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
