apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hamidgurmani/voting-app.git
    targetRevision: main
    path: infra/k8s/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: vim argocd/dev.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
