name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:

      # 🔹 Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 🔹 Login to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 🔹 Build & Push Vote
      - name: Build & Push Vote
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vote-app:latest ./vote
          docker push ${{ secrets.DOCKER_USERNAME }}/vote-app:latest

      # 🔹 Build & Push Result
      - name: Build & Push Result
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/result-app:latest ./result
          docker push ${{ secrets.DOCKER_USERNAME }}/result-app:latest

      # 🔹 Build & Push Worker
      - name: Build & Push Worker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/worker-app:latest ./worker
          docker push ${{ secrets.DOCKER_USERNAME }}/worker-app:latest

      # 🔹 Update image tag in Kubernetes manifests
      - name: Update K8s manifests
        run: |
          TAG=${{ github.sha }}

          sed -i "s|vote-app:.*|vote-app:$TAG|g" infra/k8s/base/vote/deployment.yaml
          sed -i "s|result-app:.*|result-app:$TAG|g" infra/k8s/base/result/deployment.yaml
          sed -i "s|worker-app:.*|worker-app:$TAG|g" infra/k8s/base/worker/deployment.yaml

      # 🔹 Commit & Push changes
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "update image tags" || echo "No changes to commit"
          git push oringin main
